// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aiwkdcyswrablfqmaggq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpd2tkY3lzd3JhYmxmcW1hZ2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjM5ODYsImV4cCI6MjA1NjkzOTk4Nn0.o9qs2Q7rpTiz-QDfs4M9klGYU08WkAXuJ-Z5YvBwHkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);